In [14]:
# Import the Twython class
import math as math
from twython import Twython
import pandas as pd
import json
# Loading credentials
from twitter_config import api_key,s_api_key

In [6]:
# Instantiate an object
twitter = Twython(api_key, s_api_key)

In [7]:
# Create our query
query = {'q': 'learn python',
        'result_type': 'popular',
        'count': 10,
        'lang': 'en',
        }

In [8]:


# Search tweets
dict_ = {'user': [], 'date': [], 'text': [], 'favorite_count': []}
for status in twitter.search(**query)['statuses']:
    dict_['user'].append(status['user']['screen_name'])
    dict_['date'].append(status['created_at'])
    dict_['text'].append(status['text'])
    dict_['favorite_count'].append(status['favorite_count'])

# Structure data in a pandas DataFrame for easier manipulation
df = pd.DataFrame(dict_)
df.sort_values(by='favorite_count', inplace=True, ascending=False)
df.head(5)

,user,date,text,favorite_count
0,fb_engineering,Fri Aug 07 16:21:03 +0000 2020,"We've shared details about Pysa, an open sourc...",142
1,fb_engineering,Wed Aug 05 16:02:00 +0000 2020,"We are open sourcing pcicrawler, a Python-base...",97
2,AndroidAuth,Wed Aug 05 13:10:53 +0000 2020,Python beginner‚Äôs guide ‚Äì Everything you need ...,86

In [9]:
user_tweets = twitter.get_user_timeline(screen_name='mikehelmick',
                                        include_rts=True)
for tweet in user_tweets:
    tweet['text'] = Twython.html_for_tweet(tweet)
    print(tweet['text'])

<a href="https://twitter.com/jeremylambert88" class="twython-mention">@jeremylambert88</a> <a href="https://twitter.com/SeanRossSapp" class="twython-mention">@SeanRossSapp</a> They didn‚Äôt, but I did see results on the ticker at the bottom
new <a href="https://twitter.com/AEWrestling" class="twython-mention">@AEWrestling</a> belts at Walmart..... <a href="https://t.co/0yewx7az5P" class="twython-media">pic.twitter.com/0yewx7az5P</a>
<a href="https://twitter.com/EBischoff" class="twython-mention">@EBischoff</a> <a href="https://twitter.com/HeyHeyItsConrad" class="twython-mention">@HeyHeyItsConrad</a> Catching up on some older episodes, listened to the Double or Nothing 1 episode. REALLY‚Ä¶ <a href="https://t.co/7mP4PGdkbI" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>
<a href="https://twitter.com/davidlagreca1" class="twython-mention">@davidlagreca1</a> <a href="https://twitter.com/BustedOpenRadio" class="twython-mention">@BustedOpenRadio</a> super disappointed the episode from today disappeared at 1 and hasn't been availabl‚Ä¶ <a href="https://t.co/hHlFZItlqZ" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>
<a href="https://twitter.com/HellInACellPod" class="twython-mention">@HellInACellPod</a> There were matches for the hardcore championship!
JNCO has a website <a href="https://t.co/jDsY7ZXs6B" class="twython-url">jnco.com</a> <a href="https://t.co/cOaDXk8mlS" class="twython-media">pic.twitter.com/cOaDXk8mlS</a>
<a href="https://twitter.com/webology" class="twython-mention">@webology</a> Do you have any plan for holidays? Not sure how much family you‚Äôre around but we are kind of fearing him‚Ä¶ <a href="https://t.co/CxStWbNxRk" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>
<a href="https://twitter.com/webology" class="twython-mention">@webology</a> Still super unsure of sending Michael back to preschool despite all precautions they plan on taking. How did you overcome this?
<a href="https://twitter.com/CodyRhodes" class="twython-mention">@CodyRhodes</a> know of any way I can go back and watch the first episode of dynamite that isn‚Äôt Fite?
<a href="https://twitter.com/simonw" class="twython-mention">@simonw</a> Django Webpack Loader

<a href="https://t.co/n1hSE9jUV3" class="twython-url">github.com/owais/django-w‚Ä¶</a>
Also, think of your kids. This administration wants to push back the election yet sending your kids back to school‚Ä¶ <a href="https://t.co/A7jlE1sKEU" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>
<a href="https://twitter.com/webology" class="twython-mention">@webology</a> do you have a favorite Slack notification Action for Github Actions? :D
<a href="https://twitter.com/WWEonFOX" class="twython-mention">@WWEonFOX</a> Reminds me of a few years back, I was in catering trying to go back to my table. Dwayne Johnson was in th‚Ä¶ <a href="https://t.co/fx6ivqiXK9" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>
<a href="https://twitter.com/IAmJericho" class="twython-mention">@IAmJericho</a> <a href="https://twitter.com/CodyRhodes" class="twython-mention">@CodyRhodes</a> <a href="https://twitter.com/TonyKhan" class="twython-mention">@TonyKhan</a> <a href="https://twitter.com/MATTHARDYBRAND" class="twython-mention">@MATTHARDYBRAND</a> Guys, I want to relive episode 1 of Dynamite. I‚Äôm in the US and c‚Ä¶ <a href="https://t.co/VxEURUsT2v" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>
When that NWO Wolfpac theme song hits ü§òüèº <a href="https://t.co/iYh8ISu5ei" class="twython-media">pic.twitter.com/iYh8ISu5ei</a>
<a href="https://t.co/dUBrNFNW7i" class="twython-media">pic.twitter.com/dUBrNFNW7i</a>
<a href="https://twitter.com/gctaylor" class="twython-mention">@gctaylor</a> We just bought one for my kid similar to this but plain for school this year. He has trouble saying some‚Ä¶ <a href="https://t.co/kBK5MJZFhk" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>
AEW: 845,000
NXT: 615,000
I wish <a href="https://twitter.com/luchasaurus" class="twython-mention">@luchasaurus</a> got a better fitting mask. Him constantly fixing it is really distracting :( <a href="https://twitter.com/search?q=%23AEWDynamite" class="twython-hashtag">#AEWDynamite</a>
Holy shit. This <a href="https://twitter.com/search?q=%23AEWDynamite" class="twython-hashtag">#AEWDynamite</a> is off the charts! üìà can‚Äôt wait to hear what <a href="https://twitter.com/bullyray5150" class="twython-mention">@bullyray5150</a> and <a href="https://twitter.com/davidlagreca1" class="twython-mention">@davidlagreca1</a> have to‚Ä¶ <a href="https://t.co/nIYK0VTv3l" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>

In [10]:
user_tweets = twitter.get_user_timeline(screen_name='elmo',
                                        include_rts=True, count=10)
for tweet in user_tweets:
    tweet['text'] = Twython.html_for_tweet(tweet)
    print(tweet['id'],tweet['text'])

1288172904778272771 Elmo loves selfies! Elmo and Elmo‚Äôs friends took selfies with Miss <a href="https://twitter.com/oliviawilde" class="twython-mention">@oliviawilde</a> and Miss <a href="https://twitter.com/SaraBareilles" class="twython-mention">@SaraBareilles</a> when they c‚Ä¶ <a href="https://t.co/7xDCWNxhBF" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>
1283131092829179905 Elmo‚Äôs friends <a href="https://twitter.com/Mykalscorner" class="twython-mention">@Mykalscorner</a> and <a href="https://twitter.com/HERMusicx" class="twython-mention">@HERMusicx</a> are visiting The Not-Too-Late Show this week! Elmo even has Monster Mak‚Ä¶ <a href="https://t.co/9lAQb4PwLa" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>
1281302058029719552 Elmo loved having Elmo‚Äôs friends <a href="https://twitter.com/hodakotb" class="twython-mention">@hodakotb</a> and <a href="https://twitter.com/BenSPLATT" class="twython-mention">@BenSPLATT</a> stop by Elmo‚Äôs <a href="https://twitter.com/search?q=%23NotTooLateShow" class="twython-hashtag">#NotTooLateShow</a>! Elmo learned that‚Ä¶ <a href="https://t.co/al3QR3Gr5y" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>
1281234304555720706 Elmo loved having Elmo's friend <a href="https://twitter.com/hodakotb" class="twython-mention">@hodakotb</a> visit Elmo's <a href="https://twitter.com/search?q=%23NotTooLateShow" class="twython-hashtag">#NotTooLateShow</a>! ‚ô•Ô∏è <a href="https://t.co/S3AQOwpeRp" class="twython-url">twitter.com/TODAYshow/stat‚Ä¶</a>
1266059192001060864 Yeah baby! Elmo loves singing with Elmo's friend <a href="https://twitter.com/LilNasX" class="twython-mention">@LilNasX</a>! <a href="https://t.co/BHPV9kimlD" class="twython-url">twitter.com/LilNasX/status‚Ä¶</a>
1263575883463491588 Who‚Äôs ready to see an early preview of our episode of The <a href="https://twitter.com/search?q=%23NotTooLateShow" class="twython-hashtag">#NotTooLateShow</a> with <a href="https://twitter.com/elmo" class="twython-mention">@elmo</a>? See it tonight on the Sesame‚Ä¶ <a href="https://t.co/f6FboFFRlO" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>
1263575865994227712 Yeah baby! Elmo can't wait for all of Elmo's friends to see the <a href="https://twitter.com/search?q=%23NotTooLateShow" class="twython-hashtag">#NotTooLateShow</a>! Elmo's mommy said this is the link‚Ä¶ <a href="https://t.co/lCxftftXA0" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>
1263529228114497541 <a href="https://twitter.com/CoreTeal" class="twython-mention">@CoreTeal</a> <a href="https://twitter.com/hbomax" class="twython-mention">@hbomax</a> Yeah baby! Elmo's definitely going to do some dance mooooves ha ha! <a href="https://twitter.com/search?q=%23NotTooLateShow" class="twython-hashtag">#NotTooLateShow</a>
1263520805050335238 <a href="https://twitter.com/brianstelter" class="twython-mention">@brianstelter</a> <a href="https://twitter.com/hbomax" class="twython-mention">@hbomax</a> Thank you, Sunny! Elmo loves you! ‚ô•Ô∏è <a href="https://twitter.com/search?q=%23NotTooLateShow" class="twython-hashtag">#NotTooLateShow</a>
1263520334797561856 Elmo's not sure what Elmo's crushing but if Mr. Tapper says it's a good thing then Elmo believes him! üòÖ‚Ä¶ <a href="https://t.co/RlFNniaU3q" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>

In [11]:
user_tweets = twitter.get_user_timeline(screen_name='elmo',
                                        include_rts=True, count=10, max_id=1263515657200689153-1)
for tweet in user_tweets:
    tweet['text'] = Twython.html_for_tweet(tweet)
    print(tweet['id'],tweet['text'])

1263515432599924737 <a href="https://twitter.com/TimePlaytime" class="twython-mention">@TimePlaytime</a> <a href="https://twitter.com/hbomax" class="twython-mention">@hbomax</a> Yeah baby! Elmo is so excited! <a href="https://twitter.com/search?q=%23NotTooLateShow" class="twython-hashtag">#NotTooLateShow</a>
1263515313032871936 <a href="https://twitter.com/GemBiscuits" class="twython-mention">@GemBiscuits</a> <a href="https://twitter.com/hbomax" class="twython-mention">@hbomax</a> Thank you Jayden! Elmo agrees, believing in yourself is very important! <a href="https://twitter.com/search?q=%23NotTooLateShow" class="twython-hashtag">#NotTooLateShow</a>
1263509182713659393 11 hours?! That's a lot of sheep to count ha ha! Thanks Dr. Sanjay! <a href="https://t.co/Y3v7ThOtKH" class="twython-url">twitter.com/drsanjaygupta/‚Ä¶</a>
1263502132159938560 Ha Ha! Elmo sees what Mr. Oliver did there! üëÄ <a href="https://twitter.com/search?q=%23NotTooLateShow" class="twython-hashtag">#NotTooLateShow</a> <a href="https://t.co/LuBEleoBEX" class="twython-url">twitter.com/iamjohnoliver/‚Ä¶</a>
1263501705276207105 Aw that is so kind Mr. O'Brien! Elmo will make you proud! <a href="https://twitter.com/search?q=%23NotTooLateShow" class="twython-hashtag">#NotTooLateShow</a> <a href="https://t.co/5oZajauDm5" class="twython-url">twitter.com/ConanOBrien/st‚Ä¶</a>
1254047506561982464 Thanks for helping Elmo learn about face masks <a href="https://twitter.com/drsanjaygupta" class="twython-mention">@drsanjaygupta</a>! Elmo's going to put smiley faces on Elmo's mask! <a href="https://t.co/3TU4SCvuZy" class="twython-url">twitter.com/CNN/status/125‚Ä¶</a>
1252636169352949760 Yeah baby! Elmo's so excited for The Not-Too-Late Show with all of Elmo's friends! Elmo can't wait to see who stops‚Ä¶ <a href="https://t.co/g97iXwmrw6" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>
1248376964974391296 Boy, Elmo really misses Elmo's friends sometimes. But then Elmo remembers Elmo can still talk to Elmo's friends on‚Ä¶ <a href="https://t.co/E3gKzJXkho" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>
1242476605416574978 Good morning from Sesame Street! <a href="https://twitter.com/elmo" class="twython-mention">@elmo</a> is sharing his morning routine that gets him ready for a healthy and happy d‚Ä¶ <a href="https://t.co/s1KwsHuxQY" class="twython-url">twitter.com/i/web/status/1‚Ä¶</a>
1240027017187385347 Elmo wants all of Elmo‚Äôs friends to know that Elmo loves you and Elmo hopes you are staying safe and healthy!

In [12]:
user_names = ['AbbyCadabbySST',
'SesameErnie',
'bertsesame',
'Grover',
'BigBird',
'OscarTheGrouch',
'MeCookieMonster']

In [49]:
num_tweets_to_fetch_per_char = 1000
num_queries = math.ceil(num_tweets_to_fetch_per_char/200)
tweet_idx = 0
sesame_tweets_df = pd.DataFrame(columns=['user_name','twitter_id','created_at','text'])

for user_name in user_names:
    tweets_left = num_tweets_to_fetch_per_char
    prev_max_id=0
    tweet_ct = 0
    for j in range(0,num_queries):
        if tweets_left < 200:
            querry_ct = tweets_left
        else:
            query_ct = 200
        if j==0:
            user_tweets = twitter.get_user_timeline(screen_name=user_name, include_rts=True, count=query_ct)
        else:
            user_tweets = twitter.get_user_timeline(screen_name=user_name, include_rts=True, count=query_ct, max_id=prev_max_id)
        for tweet in user_tweets:
            #tweet['text'] = Twython.html_for_tweet(tweet)
            if (tweet['text'][0:2]!='RT') and (tweet['text']!='Poof!'):
                #print(tweet_ct,tweet['id'],tweet['user']['id'],user_name,tweet['created_at'],tweet['text'])
                temp_vect = [user_name, tweet['user']['id'], tweet['created_at'][4:11]+tweet['created_at'][26:31],tweet['text']]
                sesame_tweets_df.loc[tweet_idx]=temp_vect
                tweet_ct+=1
                tweet_idx+=1
        prev_max_id=user_tweets[-1]['id']
    print(user_name,tweet_ct)

sesame_tweets_df

AbbyCadabbySST 51
SesameErnie 41
bertsesame 53
Grover 93
BigBird 269
OscarTheGrouch 129
MeCookieMonster 683

,user_name,twitter_id,created_at,text
0,AbbyCadabbySST,2496469717,Jun 23 2020,"Join me and my friend @BigBird for a magical, ..."
1,AbbyCadabbySST,2496469717,Nov 10 2019,I am so excited to celebrate Sesame Street‚Äôs 5...
2,AbbyCadabbySST,2496469717,Jul 26 2019,"Wow, the @SeattleAquarium was so magical! I sa..."
3,AbbyCadabbySST,2496469717,Jul 26 2019,Went to one of the oldest magic shops in Seatt...
4,AbbyCadabbySST,2496469717,Jul 22 2019,What a magical weekend! I loved visiting @Denv...
...,...,...,...,...
1314,MeCookieMonster,2372164754,Sep 17 2014,Thanks for your question @wickedgirl530! Me fa...
1315,MeCookieMonster,2372164754,Sep 17 2014,Hi @kemp_travis! Me welcome everyone to Sesame...
1316,MeCookieMonster,2372164754,Sep 17 2014,Cookie eating process:\n\nStep 1: locate cooki...
1317,MeCookieMonster,2372164754,Sep 16 2014,Hi! Me Cookie Monster! And me LOVE tweeting! ...
1318,MeCookieMonster,2372164754,Sep 16 2014,Hi! Me Cookie Monster! And me LOVE tweeting! ...

In [56]:
def date_conversion(date_string):
    months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
    not_done = True
    j = 0
    while not_done:
        if date_string[0:3]==months[j]:
            month_idx = j+1
            not_done = False
        elif j<11:
            j+=1
        else:
            return 'NaN'
            not_done = False
    return str(month_idx)+'/'+date_string[4:6]+'/'+date_string[7:11]

In [57]:
date_conversion('Jan 19 1980')

'1/19/1980'

In [58]:
sesame_tweets_df['created_at'] = sesame_tweets_df['created_at'].apply(date_conversion)

In [60]:
sesame_tweets_df

,user_name,twitter_id,created_at,text
0,AbbyCadabbySST,2496469717,6/23/2020,"Join me and my friend @BigBird for a magical, ..."
1,AbbyCadabbySST,2496469717,11/10/2019,I am so excited to celebrate Sesame Street‚Äôs 5...
2,AbbyCadabbySST,2496469717,7/26/2019,"Wow, the @SeattleAquarium was so magical! I sa..."
3,AbbyCadabbySST,2496469717,7/26/2019,Went to one of the oldest magic shops in Seatt...
4,AbbyCadabbySST,2496469717,7/22/2019,What a magical weekend! I loved visiting @Denv...
...,...,...,...,...
1314,MeCookieMonster,2372164754,9/17/2014,Thanks for your question @wickedgirl530! Me fa...
1315,MeCookieMonster,2372164754,9/17/2014,Hi @kemp_travis! Me welcome everyone to Sesame...
1316,MeCookieMonster,2372164754,9/17/2014,Cookie eating process:\n\nStep 1: locate cooki...
1317,MeCookieMonster,2372164754,9/16/2014,Hi! Me Cookie Monster! And me LOVE tweeting! ...
1318,MeCookieMonster,2372164754,9/16/2014,Hi! Me Cookie Monster! And me LOVE tweeting! ...

In [64]:
sesame_tweets_df.to_csv('data/sesame_tweets.csv', index=False)